---
title: "Lab04_PedroLacerda"
author: "Pedro da Costa Lacerda"
format: pdf
editor: visual
---

1) a 2)
```{r}
library(readxl)
library(tidyverse)

fname <- "WDIEXCEL.xlsx" 
file.exists(fname)

```

3) a 4)
```{r}
countries <- read_excel(fname, sheet = "Country")

countries <- countries %>%
  filter(`Country Code` %in% c("BRA", "ARG", "USA", "JPN", "DEU"))
```

5) a 8)
```{r}
WDI <- read_excel(fname, sheet = "Data")

WDI <- WDI %>%
  select(`Country Code`, `Indicator Code`, `1960`:`2018`)

WDI <- WDI %>%
  pivot_longer(
    cols = `1960`:`2018`,
    names_to = "YEAR",
    values_to = "Value"
  )

WDI <- WDI %>%
  mutate(YEAR = as.integer(YEAR))
class(WDI$YEAR)
```

9) a 10)
```{r}
WDI_final <- WDI %>%
  inner_join(countries, by = "Country Code") %>%
  pivot_wider(names_from = `Indicator Code`, values_from = Value) %>%
  select(`Country Code`, `Short Name`, YEAR, SP.DYN.CBRT.IN)

WDI_final <- WDI_final %>%
  arrange(`Short Name`, YEAR)
```

11)
```{r}
ggplot(WDI_final, aes(x = YEAR, y = SP.DYN.CBRT.IN, color = `Short Name`)) +
  geom_line(linewidth = 1) +
  labs(
    title = "Evolução da Taxa de Natalidade (1960-2018)",
    x = "Ano",
    y = "Taxa de Natalidade (Nascimentos por 1000 hab.)",
    color = "País"
  ) +
  theme_minimal()
```

```{r}
Sys.setenv(TZ = "America/Sao_Paulo")
Sys.time()
```

