---
title: "Lab02_PedroLacerda"
author: "Pedro da Costa Lacerda - 258354"
format: pdf
editor: visual
---

## 

1)

```{r}
#As estatísticas suficientes são o número de voos atrasados e o número total de voos avaliados.
```

2)

```{r}
library(dplyr)

getStats <- function(input, pos) {
  input %>%
    filter(AIRLINE %in% c("AA", "DL", "UA", "US")) %>%
    filter(!is.na(ARRIVAL_DELAY), !is.na(YEAR), !is.na(MONTH), !is.na(DAY)) %>%
    group_by(YEAR, MONTH, DAY, AIRLINE) %>%
    summarise(
      voos_atrasados = sum(ARRIVAL_DELAY > 10),
      voos_totais = n(),
      .groups = "drop"
    )
}
```

3)

```{r}
library(readr)

dados_agrupados_lotes <- read_csv_chunked(
  file = "flights.csv.zip",
  callback = DataFrameCallback$new(getStats), 
  chunk_size = 100000,
  col_types = cols_only(
    YEAR = col_integer(),
    MONTH = col_integer(),
    DAY = col_integer(),
    AIRLINE = col_character(),
    ARRIVAL_DELAY = col_double()
  )
)
```

4)

```{r}
computeStats <- function(df) {
  df %>%
    group_by(YEAR, MONTH, DAY, AIRLINE) %>%
    summarise(
      total_atrasados = sum(voos_atrasados),
      total_voos = sum(voos_totais),
      .groups = "drop"
    ) %>%
    mutate(
      Cia = AIRLINE,
      Data = as.Date(paste(YEAR, MONTH, DAY, sep = "-")),
      Perc = total_atrasados / total_voos
    ) %>%
    select(Cia, Data, Perc)
}

stats_finais <- computeStats(dados_agrupados_lotes)
```

5)

```{r}
library(ggplot2)
library(ggcal)

pal <- scale_fill_gradient(low = "#4575b4", high = "#d73027")
baseCalendario <- function(stats, cia_interesse) {
  df_cia <- stats %>% 
    filter(Cia == cia_interesse)
  calendario <- ggcal(df_cia$Data, df_cia$Perc)
  return(calendario)
}

cAA <- baseCalendario(stats_finais, "AA")
cDL <- baseCalendario(stats_finais, "DL")
cUA <- baseCalendario(stats_finais, "UA")
cUS <- baseCalendario(stats_finais, "US")

cAA + pal + ggtitle("Percentual de Atrasos (>10 min) - AA")
```

```{r}
Sys.setenv(TZ = "America/Sao_Paulo")
Sys.time()
```
